"""add hebrew_name column

Revision ID: 629a6f36f924
Revises: 
Create Date: 2026-03-25 14:13:48.656353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629a6f36f924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hebrew_name', sa.String(length=50), server_default='משתמש', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hebrew_name')

    # ### end Alembic commands ###
